### ISSUE TITLE
Investigate Failing Actor benchmarks

### ISSUE THREAD

**Issue by smarr** [smarr/SOMns#16]
At least the dictionary benchmarks are failing, probably, because I changed the dict implementation:

https://gitlab.soft.vub.ac.be/stefan.marr/SOMns/builds/738

**Comment by smarr** [comment]
Another issue is:

```
Savina.UnbalancedCobwebbedTree: iterations=1 runtime: 160087us
[truffle] opt fail         RcvdMsg(#parent:root:height:id:computation:)                |Reason com.oracle.graal.code.SourceStackTrace$1: "should never be part of a compiled AST." 
com.oracle.graal.code.SourceStackTrace$1: "should never be part of a compiled AST."
	at som.interpreter.objectstorage.InitializerFieldWrite.writeFallback(InitializerFieldWrite.java:242)
	at som.interpreter.objectstorage.InitializerFieldWriteNodeGen$FallbackNode_.execute_(InitializerFieldWriteNodeGen.java:1286)
	at som.interpreter.objectstorage.InitializerFieldWriteNodeGen$ObjectValue1Node_.execute_(InitializerFieldWriteNodeGen.java:1213)
	at som.interpreter.objectstorage.InitializerFieldWriteNodeGen$PolymorphicNode_.execute_(InitializerFieldWriteNodeGen.java:389)
	at som.interpreter.objectstorage.InitializerFieldWriteNodeGen$BaseNode_.execute(InitializerFieldWriteNodeGen.java:126)
	at som.interpreter.objectstorage.InitializerFieldWriteNodeGen.executeGeneric(InitializerFieldWriteNodeGen.java:55)
	at som.interpreter.nodes.SequenceNode.executeAllButLast(SequenceNode.java:52)
	at som.interpreter.nodes.SequenceNode.executeGeneric(SequenceNode.java:45)
	at som.interpreter.Invokable.execute(Invokable.java:33)
	at com.oracle.graal.truffle.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:477)
	at com.oracle.graal.truffle.OptimizedCallTarget.callInlined(OptimizedCallTarget.java:272)
	at com.oracle.graal.truffle.OptimizedDirectCallNode.callProxy(OptimizedDirectCallNode.java:70)
	at com.oracle.graal.truffle.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:61)
	at som.interpreter.nodes.dispatch.CachedDispatchNode.executeDispatch(CachedDispatchNode.java:39)
	at som.interpreter.nodes.MessageSendNode$GenericMessageSendNode.doPreEvaluated(MessageSendNode.java:788)
	at som.interpreter.nodes.MessageSendNode$AbstractMessageSendNode.executeGeneric(MessageSendNode.java:175)
	at som.interpreter.Invokable.execute(Invokable.java:33)
	at com.oracle.graal.truffle.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:477)
	at com.oracle.graal.truffle.OptimizedCallTarget.callInlined(OptimizedCallTarget.java:272)
	at com.oracle.graal.truffle.OptimizedDirectCallNode.callProxy(OptimizedDirectCallNode.java:70)
	at com.oracle.graal.truffle.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:61)
	at som.interpreter.nodes.dispatch.CachedDispatchNode.executeDispatch(CachedDispatchNode.java:39)
	at som.interpreter.nodes.MessageSendNode$GenericMessageSendNode.doPreEvaluated(MessageSendNode.java:788)
	at som.interpreter.actors.ReceivedMessage.execute(ReceivedMessage.java:33)
	at com.oracle.graal.truffle.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:477)
	at com.oracle.graal.truffle.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:364)
```

**Comment by smarr** [comment]
Seems stable now.
