### ISSUE TITLE
Nil>>#ifTrue: causes UnsupportedSpecializationException

### ISSUE THREAD

**Issue by daumayr** [smarr/SOMns#227]
Probably should not expose implementation details to users, unsupported operations should lead to dnu or meaningful SOM exceptions.

Stacktrace:
```
com.oracle.truffle.api.dsl.UnsupportedSpecializationException: Unexpected values provided for IfInlinedLiteralNode@79caea7f: [a Nil], [SObjectWithoutFields]
	at som.interpreter.nodes.specialized.IfInlinedLiteralNode.evaluateCondition(IfInlinedLiteralNode.java:40)
	at som.interpreter.nodes.specialized.IfInlinedLiteralNode.executeGeneric(IfInlinedLiteralNode.java:46)
        ...
```

**Comment by smarr** [comment]
Yes, it shouldn't. Seems like a simple getting-started issue, would keep it open, except if it annoys you.

**Comment by daumayr** [comment]
that was my intention, there are similar issues all around, so a lot to do for beginners

**Comment by CortezDeuce** [comment]
I'm new here and wouldn't mind taking a look at it and giving it a shot.  I haven't even gotten to my profile yet, but here is a little bit about me. I've been in school in some shape or form, for coding,since  2000. There were periods throughout that I have not coded, but am re-focusing my attention there. I have coded for a govt contractor for a time period of 3 years using c++,vb, and vbscript, but I have experience with many languages including java, java script, and web languages. I'd like to become an active contributor on the network and need to start somewhere :)   Let me know what you think. 
Thanks.
Cort

**Comment by smarr** [comment]
Hi @CortezDeuce:

Sure, if you want to dig in, you might want to start having a look at http://somns.readthedocs.io/en/dev/
It describes some basic steps on how to setup things.

I'd start to approach this issue by writing a few test cases as part of https://github.com/smarr/SOMns/blob/dev/core-lib/TestSuite/LanguageTests.ns
Great would be to test for the working and the not working conditions around all relevant `ifTrue:`, `ifFalse:` methods. Since there are some optimizations for the cases that explicit blocks (lambdas) are given, we probably also should check for those explicitly.

Please don't hesitate to ask questions.
Some of the terminology is somewhat Smalltalk specific and not necessarily generally known.

**Comment by CortezDeuce** [comment]
@smarr Thanks!
I'm working on getting everything setup per the documentation at the link(s) you've provided. Looks as if I needed ubuntu to use SOMs properly, so I'm getting that taken care of, and re-installing eclipse,soms plugin, etc. If I run into any issues that have me stuck I'll reach out to you. I'm sure there will be some questions from my end. Thanks again and speak with you soon

**Comment by smarr** [comment]
@CortezDeuce Ubuntu is not strictly required. I am using macOS. And there have been people using Fedora and other Linux variants.
It just happens to be that we haven't had anyone using something that needed specific other instructions.

The only platform currently not supported is Windows.

**Comment by CortezDeuce** [comment]
@smarr This may be silly, but running into an issue and hoping you could help me get past it. Note: using a VM with Ubuntu 32bit. Getting stuck on this line( yes "n" | ./build.sh )   It's returningthe error below. Am I unable to perform this on a 32bit system? Thanks!

  %% Make sure git submodules are up-to-date


%% JAVA_HOME=
%% Build JVMCI-enabled JVM

unknown or unsupported architecture: os=linux, machine=i686

**Comment by smarr** [comment]
@CortezDeuce If I remember correctly, Graal does not support 32-bit, 64bit would be needed. However, for this particular issue, you might not even need Graal (SOMns can run without by passing the `-G` flag).

**Comment by CortezDeuce** [comment]
@smarr  ok, that's what I was figuring, but was hesitant to move on, skipping a step. Thanks, I'll continue on  with the steps listed.

**Comment by smarr** [comment]
@CortezDeuce once #232 is merged, things should be simpler, and documentation improved hopefully, too
