### ISSUE TITLE
SafepointPhaseTest fails in testSafepointStorm

### ISSUE THREAD

**Issue by smarr** [smarr/SOMns#356]
An earlier attempt to investigate the issue lead me to add try/finally around sensitive operations in the `ObjectTransitionSafepoint`, and I initially thought that would fix it, the test started to pass, but it seems to be failing again: https://github.com/smarr/SOMns/commit/bbdd7b4c300e4527f9a534f19eb62533c965284e

Next thing to investigate is whether register/unregister operations play correctly with the assumption of having matching pairs of phases in the phaser.

Current failures look like:

```
    [junit] junit.framework.AssertionFailedError
     [junit] 	at org.junit.Assert.fail(Assert.java:86)
     [junit] 	at org.junit.Assert.assertTrue(Assert.java:41)
     [junit] 	at org.junit.Assert.assertTrue(Assert.java:52)
     [junit] 	at som.tests.ParallelHelper.executeNTimesInParallel(ParallelHelper.java:56)
     [junit] 	at som.interpreter.objectstorage.SafepointPhaserTest.testSafepointStorm(SafepointPhaserTest.java:93)
```

It only fails on `yuria`, not locally.

**Comment by smarr** [comment]
After further investigation, this seemed to be caused by timeouts only and no further issues are currently observed.

I consider it closed with #357 for the moment.
